<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('theloai')->insert([
            ['id'=>1,'ten'=>'Vui chơi', 'tenkhongdau'=>'Vui-choi'],
            ['id'=>2,'ten'=>'Học tập', 'tenkhongdau'=>'Hoc-tap'],
            ['id'=>3,'ten'=>'Nghỉ ngơi', 'tenkhongdau'=>'Nghi-ngoi'],
            ['id'=>4,'ten'=>'Môi trường', 'tenkhongdau'=>'Moi-truong'],
            ['id'=>5,'ten'=>'Hoạt động', 'tenkhongdau'=>'Hoat-dong'],
            ['id'=>6,'ten'=>'Thông báo', 'tenkhongdau'=>'Thong-bao'],
            ['id'=>7,'ten'=>'Học phí', 'tenkhongdau'=>'Hoc-phi'],
        ]);
        DB::table('loaitin')->insert([
            ['id'=>1,'idtheloai'=>'1', 'ten'=>'Giờ giải lao sáng', 'tenkhongdau'=>'th-nghiem', 'id_theloai'=>'1'],
            ['id'=>2,'idtheloai'=>'4', 'ten'=>'Khu tập hợp', 'tenkhongdau'=>'ky-thuat', 'id_theloai'=>'4'],
            ['id'=>3,'idtheloai'=>'2', 'ten'=>'Học buổi sáng', 'tenkhongdau'=>'c-ng-ng', 'id_theloai'=>'2'],
            ['id'=>4,'idtheloai'=>'6', 'ten'=>'Thông báo nghỉ dịch', 'tenkhongdau'=>'sang-tao', 'id_theloai'=>'6'],
            ['id'=>5,'idtheloai'=>'5', 'ten'=>'Hoạt động ngoại khóa', 'tenkhongdau'=>'hop-t-ng-b-', 'id_theloai'=>'5'],
            ['id'=>6,'idtheloai'=>'1', 'ten'=>'Giờ giải lao chiều', 'tenkhongdau'=>'bo-phieu', 'id_theloai'=>'1'],
            ['id'=>7,'idtheloai'=>'7', 'ten'=>'Tăng phí lắp đặt', 'tenkhongdau'=>'dan-chu', 'id_theloai'=>'7'],
            ['id'=>8,'idtheloai'=>'3', 'ten'=>'Ngủ trưa', 'tenkhongdau'=>'hop-t-ng-b-chi', 'id_theloai'=>'3'],
            ['id'=>9,'idtheloai'=>'2', 'ten'=>'Học biểu chiều', 'tenkhongdau'=>'phong-canh', 'id_theloai'=>'2'],
            ['id'=>10,'idtheloai'=>'6', 'ten'=>'Thông báo họp phụ huynh', 'tenkhongdau'=>'ky-thuat', 'id_theloai'=>'6'],
            ['id'=>11,'idtheloai'=>'4', 'ten'=>'Sân chơi', 'tenkhongdau'=>'th-nghiem', 'id_theloai'=>'4'],
            ['id'=>12,'idtheloai'=>'5', 'ten'=>'Hoạt động tham quan', 'tenkhongdau'=>'che-tao', 'id_theloai'=>'5'],
            ['id'=>13,'idtheloai'=>'3', 'ten'=>'Ăn trưa', 'tenkhongdau'=>'c-ng-ng', 'id_theloai'=>'3'],
            ['id'=>14,'idtheloai'=>'7', 'ten'=>'Tăng phí sinh hoạt', 'tenkhongdau'=>'sang-tao', 'id_theloai'=>'7'],
            ['id'=>15,'idtheloai'=>'5', 'ten'=>'Hoạt động ngoài giờ', 'tenkhongdau'=>'hop-t-ng-b-', 'id_theloai'=>'5'],
            ['id'=>16,'idtheloai'=>'1', 'ten'=>'Giờ giải lao thêm', 'tenkhongdau'=>'bo-phieu', 'id_theloai'=>'1'],
            ['id'=>18,'idtheloai'=>'6', 'ten'=>'Thông báo nghỉ học', 'tenkhongdau'=>'hop-t-ng-b-chi', 'id_theloai'=>'6'],
            ['id'=>19,'idtheloai'=>'2', 'ten'=>'Học ngoại khóa', 'tenkhongdau'=>'phong-canh', 'id_theloai'=>'2'],
            ['id'=>20,'idtheloai'=>'4', 'ten'=>'Phòng học', 'tenkhongdau'=>'che-tao', 'id_theloai'=>'4'],
        ]);
        DB::table('tintuc')->insert([
            ['id'=>1,'tieude'=>'Phòng học hàng ngày', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Phòng học đầy đủ các dụng cụ cần thiết với các bé',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'1.jpg', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'20', 'loaitin_id'=>'20'],
            ['id'=>2,'tieude'=>'Hôm nay ăn gì lo ??', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'2.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>3,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'HT5',
                'noidung'=>'Đi học5',
                'hinh'=>'3.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>' 1'],
            ['id'=>4,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'ạo giống mới cho nông',
                'noidung'=>'tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'4.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'5', 'loaitin_id'=>'5'],
            ['id'=>5,'tieude'=>'Hiển thị10', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Đã thành công tạo giống mới',
                'noidung'=>'Đã thành công tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'5.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>6,'tieude'=>'Hiển thị3', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'HT3',
                'noidung'=>'Đi học3',
                'hinh'=>'6.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>7,'tieude'=>'nghiệp phát triển ngông', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'Đi nghiệp phát triển ngông',
                'hinh'=>'7.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>8,'tieude'=>'Phát triển', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'phát Đi học1',
                'noidung'=>'Đi học',
                'hinh'=>'8.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>9,'tieude'=>'triển ngông', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển',
                'hinh'=>'9.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>10,'tieude'=>'Phát triển', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển ngông',
                'hinh'=>'10.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>11,'tieude'=>'Hôm nay ăn cái gì ??', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'11.png', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>12,'tieude'=>'Hôm nay ăn gì lo ??', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'12.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>13,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'HT5',
                'noidung'=>'Đi học5',
                'hinh'=>'13.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>' 1'],
            ['id'=>14,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'ạo giống mới cho nông',
                'noidung'=>'tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'14.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'5', 'loaitin_id'=>'5'],
            ['id'=>15,'tieude'=>'Hiển thị10', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Đã thành công tạo giống mới',
                'noidung'=>'Đã thành công tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'15.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>16,'tieude'=>'Hiển thị3', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'HT3',
                'noidung'=>'Đi học3',
                'hinh'=>'16.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>17,'tieude'=>'nghiệp phát triển ngông', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'Đi nghiệp phát triển ngông',
                'hinh'=>'17.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>18,'tieude'=>'Phát triển', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'phát Đi học1',
                'noidung'=>'Đi học',
                'hinh'=>'18.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>19,'tieude'=>'triển ngông', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển',
                'hinh'=>'19.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>20,'tieude'=>'Phát triển', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển ngông',
                'hinh'=>'20.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>21,'tieude'=>'Hôm nay ăn cái gì ??', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'21.png', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>22,'tieude'=>'Hôm nay ăn gì lo ??', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'22.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>23,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'HT5',
                'noidung'=>'Đi học5',
                'hinh'=>'23.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>' 1'],
            ['id'=>24,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'ạo giống mới cho nông',
                'noidung'=>'tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'24.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'5', 'loaitin_id'=>'5'],
            ['id'=>25,'tieude'=>'Hiển thị10', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Đã thành công tạo giống mới',
                'noidung'=>'Đã thành công tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'25.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>26,'tieude'=>'Hiển thị3', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'HT3',
                'noidung'=>'Đi học3',
                'hinh'=>'26.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>27,'tieude'=>'nghiệp phát triển ngông', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'Đi nghiệp phát triển ngông',
                'hinh'=>'27.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>28,'tieude'=>'Phát triển', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'phát Đi học1',
                'noidung'=>'Đi học',
                'hinh'=>'28.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>29,'tieude'=>'triển ngông', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển',
                'hinh'=>'29.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>30,'tieude'=>'Phát triển', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển ngông',
                'hinh'=>'30.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>31,'tieude'=>'Hôm nay ăn cái gì ??', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'31.png', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>32,'tieude'=>'Hôm nay ăn gì lo ??', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'32.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>33,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'HT5',
                'noidung'=>'Đi học5',
                'hinh'=>'33.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>' 1'],
            ['id'=>34,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'ạo giống mới cho nông',
                'noidung'=>'tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'34.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'5', 'loaitin_id'=>'5'],
            ['id'=>35,'tieude'=>'Hiển thị10', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Đã thành công tạo giống mới',
                'noidung'=>'Đã thành công tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'35.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>36,'tieude'=>'Hiển thị3', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'HT3',
                'noidung'=>'Đi học3',
                'hinh'=>'36.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>37,'tieude'=>'nghiệp phát triển ngông', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'Đi nghiệp phát triển ngông',
                'hinh'=>'37.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>38,'tieude'=>'Phát triển', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'phát Đi học1',
                'noidung'=>'Đi học',
                'hinh'=>'38.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>39,'tieude'=>'triển ngông', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển',
                'hinh'=>'39.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>40,'tieude'=>'Phát triển', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển ngông',
                'hinh'=>'40.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>41,'tieude'=>'Hôm nay ăn cái gì ??', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'41.png', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>42,'tieude'=>'Hôm nay ăn gì lo ??', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'42.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>43,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'HT5',
                'noidung'=>'Đi học5',
                'hinh'=>'43.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>' 1'],
            ['id'=>44,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'ạo giống mới cho nông',
                'noidung'=>'tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'44.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'5', 'loaitin_id'=>'5'],
            ['id'=>45,'tieude'=>'Hiển thị10', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Đã thành công tạo giống mới',
                'noidung'=>'Đã thành công tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'45.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>46,'tieude'=>'Hiển thị3', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'HT3',
                'noidung'=>'Đi học3',
                'hinh'=>'46.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>47,'tieude'=>'nghiệp phát triển ngông', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'Đi nghiệp phát triển ngông',
                'hinh'=>'47.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>48,'tieude'=>'Phát triển', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'phát Đi học1',
                'noidung'=>'Đi học',
                'hinh'=>'48.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>49,'tieude'=>'triển ngông', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển',
                'hinh'=>'49.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>50,'tieude'=>'Phát triển', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển ngông',
                'hinh'=>'50.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>51,'tieude'=>'Hôm nay ăn cái gì ??', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'51.png', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>52,'tieude'=>'Hôm nay ăn gì lo ??', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Đi học1',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'52.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>53,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'HT5',
                'noidung'=>'Đi học5',
                'hinh'=>'53.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>' 1'],
            ['id'=>54,'tieude'=>'Hôm nay ăn gì ta ??', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'ạo giống mới cho nông',
                'noidung'=>'tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'54.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'5', 'loaitin_id'=>'5'],
            ['id'=>55,'tieude'=>'Hiển thị10', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Đã thành công tạo giống mới',
                'noidung'=>'Đã thành công tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'55.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>56,'tieude'=>'Hiển thị3', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'HT3',
                'noidung'=>'Đi học3',
                'hinh'=>'56.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>57,'tieude'=>'nghiệp phát triển ngông', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'Đi nghiệp phát triển ngông',
                'hinh'=>'57.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>58,'tieude'=>'Phát triển', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'phát Đi học1',
                'noidung'=>'Đi học',
                'hinh'=>'58.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'1'],
            ['id'=>59,'tieude'=>'triển ngông', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển',
                'hinh'=>'59.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>60,'tieude'=>'Phát triển', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'nghiệp phát triển ngông',
                'noidung'=>'nghiệp phát triển ngông',
                'hinh'=>'60.png','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
        ]);
        DB::table('comment')->insert([
            ['id'=>1,'iduser'=>'1', 'idtintuc'=>'1', 'noidung'=>'Hay', 'tintuc_id'=>'1'],
            ['id'=>2,'iduser'=>'1', 'idtintuc'=>'1', 'noidung'=>'Hay', 'tintuc_id'=>'1'],
            ['id'=>3,'iduser'=>'1', 'idtintuc'=>'1', 'noidung'=>'Hay', 'tintuc_id'=>'1'],
            ['id'=>4,'iduser'=>'1', 'idtintuc'=>'1', 'noidung'=>'Hay', 'tintuc_id'=>'1'],
            ['id'=>5,'iduser'=>'1', 'idtintuc'=>'1', 'noidung'=>'Hay', 'tintuc_id'=>'1'],
            ['id'=>6,'iduser'=>'1', 'idtintuc'=>'1', 'noidung'=>'Hay', 'tintuc_id'=>'1'],
            ['id'=>7,'iduser'=>'1', 'idtintuc'=>'1', 'noidung'=>'Hay', 'tintuc_id'=>'1'],
        ]);
//        DB::table('commentdetail')->insert([
//            ['id'=>1,'iduser'=>'1', 'idcomment'=>'1', 'noidung'=>'Hay', 'tintuc_id'=>'1'],
//        ]);
        DB::table('slide')->insert([
            ['id'=>1,'ten'=>'slide 1', 'hinh'=>'sl.png', 'noidung'=>'Hay1', 'link'=>'11'],
            ['id'=>2,'ten'=>'slide 2', 'hinh'=>'sl2.jpg', 'noidung'=>'Hay2', 'link'=>'12'],
            ['id'=>3,'ten'=>'slide 3', 'hinh'=>'sl3.jpg', 'noidung'=>'Hay3', 'link'=>'13'],
        ]);
        DB::table('users')->insert([
            ['id'=>1,'username'=>'Nguyễn Quyết', 'name'=>'Chiến', 'avatar'=>'111.jpg', 'email'=>'chien@gmail.com',
                'password'=>bcrypt('chien@123'), 'phoneNumber'=>'0963328520', 'birthYear'=>'11/10/2000',
                'active'=>'1', 'streetInformation'=>'Thôn 7, Trung Châu, Đan Phượng', 'province'=>'Hà Nội',
                'summary'=>'Thích đọc truyện, xem phim, ăn, ngủ :3', 'level'=>'1', 'comment_id'=>'1'],
            ['id'=>2,'username'=>'Trần Việt', 'name'=>'Chinh', 'avatar'=>'11.jpg', 'email'=>'chinh@gmail.com',
                'password'=>bcrypt('chinh@123'), 'phoneNumber'=>'0963328520', 'birthYear'=>'11/10/2000',
                'active'=>'1', 'streetInformation'=>'Thôn 10, Trung Châu, Đan Phượng', 'province'=>'Hà Nội',
                'summary'=>'Thích đọc truyện, xem phim, ăn, ngủ :3', 'level'=>'0', 'comment_id'=>'1'],
        ]);
    }
}
